### ISSUE TITLE
[Bug] 无法加载背景脚本“serviceWorker.js”。 无法加载清单。

### ISSUE THREAD

**Issue by BruceZhang1993** [kenmingwang/azusa-player#1]
加载插件提示 `无法加载背景脚本“serviceWorker.js”。 无法加载清单。`

- 系统版本  Arch Linux x86_64 (rolling)
- Chrome 版本  97.0.4692.99（正式版本） （64 位）
- 插件版本  0.0.0.2
- 复现步骤  开发者模式加载插件

![image](https://user-images.githubusercontent.com/6873988/151697819-4578e3bc-7090-4304-ac81-608b398dcea7.png)

**Comment by kenmingwang** [comment]
感谢反馈 晚点我会进行排查

**Comment by BruceZhang1993** [comment]
似乎是文件名大小写问题，改为 serviceWorker.js 可以运行了，谢谢～

**Comment by kenmingwang** [comment]
感谢！手头没Linux机器还在琢磨怎么测试来着

**Comment by kenmingwang** [comment]
https://github.com/kenmingwang/azusa-player/pull/6/commits/ce6be55cc9fcde20a02d8694f293262fd20d14c7
