### ISSUE TITLE
删除BUG

### ISSUE THREAD

**Issue by MrIsland** [kenmingwang/azusa-player#10]
大佬您好，这个播放器等了好久终于等到有人做了 hhhh。
在使用的过程中，发现删除后面的歌曲的时候 他会自动删除第一首歌曲？ 您看这个问题是什么情况呢？

**Comment by kenmingwang** [comment]
已收到！近期会修复的，感谢反馈！

**Comment by kenmingwang** [comment]
会在这个issue里解决: https://github.com/kenmingwang/azusa-player/issues/13
