### ISSUE TITLE
FeatureRequest: 希望可以通过合集的BVid搜索后直接添加歌单

### ISSUE THREAD

**Issue by feenammm** [kenmingwang/azusa-player#11]
目前的操作我摸索了下，大概需要
1.先在右侧建立歌单
2.通过BVid搜索
3.一首一首添加
希望能够添加批量或者直接导入合集的功能

**Comment by kenmingwang** [comment]
感谢反馈！全部（非自选批量）导入歌单功能是支持的，在右侧搜索歌单处有个➕号，可以把整个搜索歌单添加到本地歌单里。

批量添加在todo里了！

**Comment by feenammm** [comment]
感谢讲解，我主要是想建立一个原标题的歌单，试了一下可以达到效果。
不过或许可以在点击搜索歌单那里的 “添加到收藏歌单” 按钮时，弹窗内加入一个选项可以直接新建本地歌单标题为对应BVid歌单的标题，这样会更加方便。

**Comment by kenmingwang** [comment]
https://github.com/kenmingwang/azusa-player/pull/21
