### ISSUE TITLE
BugFix: 启用插件导致腾讯文档无权限需不断登录

### ISSUE THREAD

**Issue by feenammm** [kenmingwang/azusa-player#15]
如标题，启用插件后腾讯文档登录后页面显示无权限需不断登录，停用后恢复

**Comment by Yalois** [comment]
我也是，微信公众号网站无法正常登录，无法加载二维码，之前有cookie的时候无法正常加载数据。

**Comment by feenammm** [comment]
目前发现需要手动设置可以解决问题的方式
在chrome浏览器扩展程序页面，找到扩展程序，点击详情，设置有权访问的网站，选择在特定网站上，配置   *://api.bilibili.com/*

**Comment by Yalois** [comment]
> beta版本应该修复了问题，可以的话麻烦帮忙测试下，感谢！
> 
> https://github.com/kenmingwang/azusa-player/releases/tag/pre-release-1.1.0.0

ok了

**Comment by simonire** [comment]
我超，我说为什么腾讯文档打不开

**Comment by feenammm** [comment]
新版使用时没问题了，感谢
