### ISSUE TITLE
BugFix: upos-sz-mirrorcosov.bilivideo.com會給移動端的user-agent 403

### ISSUE THREAD

**Issue by lovegaoshi** [kenmingwang/azusa-player#17]
目前所有musicSrc源於https://upos-sz-mirrorcosov.bilivideo.com/ 的在移動端的請求會403，桌面端則不會；在chrome控制臺設置爲移動端即可復現

將UA設置爲桌面端就可以解決這個問題
在rules.json，bilvideo.com的requestHeaders内加入
`{ "header": "User-Agent", "operation": "set", "value": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" }`
即可

**Comment by kenmingwang** [comment]
谢谢反馈！因为native移动端已经在开发中，暂时不打算强行让插件支持移动端，有需要的同学可以按照楼主的方法修复下。
