### ISSUE TITLE
BugFix: 1.0.0.1版本 audio error

### ISSUE THREAD

**Issue by MerlinCN** [kenmingwang/azusa-player#19]
无法播放音乐
![image](https://user-images.githubusercontent.com/37311477/197610280-8d2b91ac-27e9-42e2-a1c3-a38d8ba31a7a.png)

**Comment by kenmingwang** [comment]
hmm我这里还一切正常，有可能是地域/ip问题，或者b站偶尔抽风。问题还在持续吗？

**Comment by MerlinCN** [comment]
> hmm我这里还一切正常，有可能是地域/ip问题，或者b站偶尔抽风。问题还在持续吗？

把所有插件关了还是有，代理也关了，edge和chrome都试了

**Comment by kenmingwang** [comment]
beta版本应该修复了问题，可以的话麻烦帮忙测试下，感谢！

https://github.com/kenmingwang/azusa-player/releases/tag/pre-release-1.1.0.0

**Comment by MerlinCN** [comment]
已正常
