### ISSUE TITLE
可以给这个扩展单独挂个代理吗

### ISSUE THREAD

**Issue by 962725312** [kenmingwang/azusa-player#20]
试了几个域名都有问题，不然vpn只能开全局，有点折磨

**Comment by docase** [comment]
有的时候bilibili api返回的baseurl可能不能用，backupurl却可能可以用，希望作者加一个检测url可用性

**Comment by docase** [comment]
有的时候bilibili api返回的baseurl可能不能用，backupurl却可能可以用，希望作者加一个检测url可用性

**Comment by kenmingwang** [comment]
> 试了几个域名都有问题，不然vpn只能开全局，有点折磨

可以给个坏域名例子吗？本地(国外)测试baseurl和backuourl都可用

**Comment by kenmingwang** [comment]
beta版本应该修复了问题，可以的话麻烦帮忙测试下，感谢！

https://github.com/kenmingwang/azusa-player/releases/tag/pre-release-1.1.0.0

**Comment by docase** [comment]
beta版不挂代理也能用了

**Comment by 962725312** [comment]
修复了，谢谢老哥 👍
