### ISSUE TITLE
希望可以加个视频合集的列表识别

### ISSUE THREAD

**Issue by Yalois** [kenmingwang/azusa-player#22]
例如这个链接：https://space.bilibili.com/102539476/channel/collectiondetail?sid=584726
这个插件好像只能识别视频选集

**Comment by kenmingwang** [comment]
谢谢反馈，@lovegaoshi 已在 https://github.com/kenmingwang/azusa-player/pull/21 添加了该功能，[Beta](https://github.com/kenmingwang/azusa-player/releases/tag/pre-release-1.1.0.0)版已支持，正式版预计这周末会更新
