### ISSUE TITLE
字体缩放问题

### ISSUE THREAD

**Issue by sileneer** [kenmingwang/azusa-player#25]
![image](https://user-images.githubusercontent.com/31238371/200159897-389cfc00-9f22-4a02-a25a-e7524dca7a96.png)

如图，安装后进入默认好孩梓的歌单，歌单显示的字体会很小
浏览器：Edge 107.0.1418.26

**Comment by 12ff54e** [comment]
在这个 [PR](https://github.com/kenmingwang/azusa-player/pull/16) 里面，字号被增大了，但是作者还没有发布新版本。你可以试试离线安装 [beta版](https://github.com/kenmingwang/azusa-player/releases/tag/pre-release-1.1.0.0)

**Comment by kenmingwang** [comment]
https://github.com/kenmingwang/azusa-player/pull/23

**Comment by kenmingwang** [comment]
> ![image](https://user-images.githubusercontent.com/31238371/200159897-389cfc00-9f22-4a02-a25a-e7524dca7a96.png)
> 
> 如图，安装后进入默认好孩梓的歌单，歌单显示的字体会很小 浏览器：Edge 107.0.1418.26

应该已经修复，顺便问下屏幕分辨率和浏览器放大率能提供下吗
