### ISSUE TITLE
希望在“搜索歌曲”的结果中删除歌曲后能保持搜索的结果

### ISSUE THREAD

**Issue by 12ff54e** [kenmingwang/azusa-player#26]
有些录播组会加上防撞车的P2，名字大多都一样。在添加歌单之后我会搜索这些条目并且删除它们，如果删除之后能保持搜索的结果能方便很多。如果作者也认同的话我可以提交PR。

**Comment by kenmingwang** [comment]
你好感谢反馈，有点没理解，能举个BV号的例子吗？

**Comment by 12ff54e** [comment]
> 你好感谢反馈，有点没理解，能举个BV号的例子吗？

可以看一下这个收藏夹：1792572149，里面有很多视频的P2标题是“❤❤❤❤❤”，就是为了防撞车添加的

**Comment by kenmingwang** [comment]
> > 你好感谢反馈，有点没理解，能举个BV号的例子吗？
> 
> 可以看一下这个收藏夹：1792572149，里面有很多视频的P2标题是“❤❤❤❤❤”，就是为了防撞车添加的

Ok懂了懂了，你是打算在搜索的时候过滤掉这些吗，感觉可以按时间来过滤，视频时长小于5s可以直接过滤掉之类的？可以在搜索旁边加个选项框来开关这个过滤功能

> 如果删除之后能保持搜索的结果能方便很多

主要是这句话没太理解

**Comment by 12ff54e** [comment]
哦哦，你说的是自动化的解决方案，但我现在是手动去除的。

> >如果删除之后能保持搜索的结果能方便很多
>
> 主要是这句话没太理解

我描述一下我的做法，你试一下就明白了：当添加了收藏夹之后，我会在搜索歌曲那里填❤❤❤❤❤，这样就会将所有这个标题的视频筛出来，然后我再去逐个点删除。但是删除一个之后整个歌单会重新加载，搜索的结果就没了；如果删除之后还是保持之前的搜索结果，那点删除就快多了。

PS：就算之后有了按时长过滤的功能，我感觉删除后保持搜索结果这个行为还是比较符合大部分人的习惯的。

**Comment by lovegaoshi** [comment]
这个删除能用我还是挺惊讶的，毕竟handleDelteFromSearchList接收的参数是index而不是视频cid/song.id，按理说在搜索的子列表里删除应该会导致index对不上而删错

**Comment by 12ff54e** [comment]
> 这个删除能用我还是挺惊讶的，毕竟handleDelteFromSearchList接收的参数是index而不是视频cid/song.id，按理说在搜索的子列表里删除应该会导致index对不上而删错

因为现在的 `handleDelteFromSearchList` 接收的参数就是视频的 id：
https://github.com/kenmingwang/azusa-player/blob/59e1a5875b1c19254b3e5ef553349b8fb23eb768/src/components/FavList.js#L94-L95

**Comment by 12ff54e** [comment]
PR https://github.com/kenmingwang/azusa-player/pull/27 已合并，问题解决了。
