### ISSUE TITLE
默认歌单的请求被B站禁止了

### ISSUE THREAD

**Issue by tieniu1** [kenmingwang/azusa-player#38]
<img width="1680" alt="Snipaste_2023-10-19_10-27-02" src="https://github.com/kenmingwang/azusa-player/assets/49060203/3b76d445-9fdc-4d5d-959c-16f40e3be301">

**Comment by lovegaoshi** [comment]
我默认歌单倒是没问题。重构的时候发现fetch params只要credentials设置了就会412
https://github.com/lovegaoshi/azusa-player/blob/nox-player/src/utils/BiliFetch.ts#L4
现在我所有需要credentials操作的都要另外重写

**Comment by tieniu1** [comment]
可能是调接口调的太快了，昨天又出现了，等了几分钟就好了。
