### ISSUE TITLE
[Bug]audio error

### ISSUE THREAD

**Issue by komiblog** [kenmingwang/azusa-player#40]
![图片](https://github.com/kenmingwang/azusa-player/assets/102006886/3d1b73f1-ab08-43b9-95f9-2c7cf71c56b5)
怀疑是B站抽风，不知道在插件端能不能改善，希望作者有空能解决一下。
现在的解决方法就是挂代理。

**Comment by komiblog** [comment]
挂代理也是一样，请求发到akamaized.net就可以播放，发到bilivideo.com就不能播放。

**Comment by lovegaoshi** [comment]
bilivideo得加referrer
https://github.com/lovegaoshi/azusa-player/blob/nox-player/public/rules.json#L12

**Comment by komiblog** [comment]
感谢解答。好像是brave浏览器限制了referrer，且不能解除，我再想想其他办法

**Comment by lovegaoshi** [comment]
讲错了，azusa player是漏了user-agent
试试nox这个 如果nox可以 你把UA加上提个PR即可

https://microsoftedge.microsoft.com/addons/detail/jlhdkgcfcdabihmdkhdjlcppdlnlfogp

**Comment by komiblog** [comment]
现在是这种现象：在brave浏览器上电梓播放器不能正常播放，在chrome浏览器上可以，nox在两个浏览器上都可以正常使用。
brave浏览器+电梓播放器：
![屏幕截图](https://github.com/kenmingwang/azusa-player/assets/128768794/eadb52bc-62c0-451e-919e-4aca587c8dec)
brave浏览器+nox-player：
![屏幕截图](https://github.com/kenmingwang/azusa-player/assets/128768794/b115460f-04fb-45ed-8b88-9910e7c7a199)
chrome浏览器+电梓播放器：
![屏幕截图 2023-12-13 142115](https://github.com/kenmingwang/azusa-player/assets/128768794/67824714-ea5a-45ce-aa6c-9968e673562f)

区别似乎就在referer，但是我不知道该怎么改

**Comment by lovegaoshi** [comment]
你直接把我的rules. json复制到阿紫的 编译看看
https://github.com/lovegaoshi/azusa-player/blob/nox-player/public/rules.json#L12

**Comment by komiblog** [comment]
还真是这个原因，我把 build.zip解压出的包中的rules.json 替换成你那份，问题就解决了O(∩_∩)O
（因为没试过编译项目，顺便请教一下咋编译项目
我去提交个PR

**Comment by lovegaoshi** [comment]
git clone
yarn
yarn build

**Comment by komiblog** [comment]
感谢指点，已提交PR
