### ISSUE TITLE
能使用pake把网页端打包成桌面端应用吗

### ISSUE THREAD

**Issue by Takenforgranted** [kenmingwang/azusa-player#53]
自己使用浏览器自带的传统的electron打包，整个搞的可以说是臃肿不堪，很难搞，而且pake自身就是高度自制化的方便网页端的开发者将自己的成果转桌面端的。

最近打算干一票大的吗？

偶内盖，只要你能为大家更新，我什么都会做的!瓦↑塔→西↓……

**Comment by lovegaoshi** [comment]
插件就是桌面端。。？
pake打包并没有如electron提供特殊原生功能 相比插件没意义
况且项目用了大量chrome插件独有的功能需要大重构
